// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_dvUAJd6fMiXtCdM84ljB83oizP2MyM',
    appId: '1:37857241766:web:f26c85be5635e6c33ca267',
    messagingSenderId: '37857241766',
    projectId: 'alchemist-shop-1bb1c',
    authDomain: 'alchemist-shop-1bb1c.firebaseapp.com',
    storageBucket: 'alchemist-shop-1bb1c.firebasestorage.app',
    measurementId: 'G-2HH80QW99Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC22Bmybpn7EBjfZ6FjDkNp2yv5rMMZp28',
    appId: '1:37857241766:android:dd332ff59c9972713ca267',
    messagingSenderId: '37857241766',
    projectId: 'alchemist-shop-1bb1c',
    storageBucket: 'alchemist-shop-1bb1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1F1jH-eeEv3CY_uvpSnozbNbHprBRbIs',
    appId: '1:37857241766:ios:a13083c4400d4ba33ca267',
    messagingSenderId: '37857241766',
    projectId: 'alchemist-shop-1bb1c',
    storageBucket: 'alchemist-shop-1bb1c.firebasestorage.app',
    iosBundleId: 'com.example.alchemiststock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1F1jH-eeEv3CY_uvpSnozbNbHprBRbIs',
    appId: '1:37857241766:ios:a13083c4400d4ba33ca267',
    messagingSenderId: '37857241766',
    projectId: 'alchemist-shop-1bb1c',
    storageBucket: 'alchemist-shop-1bb1c.firebasestorage.app',
    iosBundleId: 'com.example.alchemiststock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn_dvUAJd6fMiXtCdM84ljB83oizP2MyM',
    appId: '1:37857241766:web:115eeac814be98293ca267',
    messagingSenderId: '37857241766',
    projectId: 'alchemist-shop-1bb1c',
    authDomain: 'alchemist-shop-1bb1c.firebaseapp.com',
    storageBucket: 'alchemist-shop-1bb1c.firebasestorage.app',
    measurementId: 'G-2JMQV9G59D',
  );
}
